improve project file based building running editing with CleanIDE a nitrile project

diff --git a/bin-nitrile/check-required-cmds b/bin-nitrile/check-required-cmds
--- a/bin-nitrile/check-required-cmds
+++ b/bin-nitrile/check-required-cmds
@@ -1,11 +1,14 @@
 check_required_commands() {
-  for cmd in "$@"; do
-    if ! command -v "$cmd" &> /dev/null; then
-      echo "Error: '$cmd' is not installed. Please install '$cmd' before running this command." >&2
-      exit 1
-    fi
-  done
-  local cmd="$1"
+    for cmd in "$@"; do
+        if ! command -v "$cmd" &>/dev/null; then
+            echo "ERROR: '$cmd' is not installed. Please install '$cmd' before running this command." >&2
+            if [[ "$cmd" == "yq" ]]; then
+                echo "yq can be downloaded from https://github.com/mikefarah/yq/releases/"
+            fi
+            exit 1
+        fi
+    done
+    local cmd="$1"
 }
 
 check_required_commands "$@"
